common:
    lid_topic:  "/points2"
    imu_topic:  "/imu"

preprocess:
    lidar_type: 3                # L515 LiDAR
    scan_line: 64
    blind: 0.01
    point_filter_num: 5
    calib_laser: false

mapping:
    down_sample_size: 0.3
    max_iteration: 3
    voxel_size: 0.25
    max_layer: 2 
    layer_point_size: [20, 10, 10, 5, 5]
    plannar_threshold: 0.01
    max_points_size: 200
    max_cov_points_size: 200

noise_model:
    ranging_cov: 0.05
    angle_cov: 0.25
    acc_cov_scale: 0.1
    gyr_cov_scale: 0.1

imu:
    imu_en: true
    extrinsic_T: [ -0.047, 0.0285, 0.0033]
    extrinsic_R: [ -0.00061492, 0.00730016, -0.999973, 
                   -0.999996, -0.00270155, 0.000595212, 
                   -0.00269713, 0.99997, 0.00730179]


visualization:
    pub_voxel_map: false
    publish_max_voxel_layer: 1         # only publish 0,1 layer's plane
    pub_point_cloud: true
    dense_map_enable: true
    pub_point_cloud_skip: 200            # publish one points per five points

Result:
    write_kitti_log: false
    result_path: ""
